//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///namespace {{moduleName}};
        ///
        ///use Zend\Router\Http\Segment;
        ///use Zend\ServiceManager\Factory\InvokableFactory;
        ///
        ///return [
        ///    &apos;router&apos; =&gt; [
        ///        &apos;routes&apos; =&gt; [
        ///            &apos;{{moduleUrl}}&apos; =&gt; [
        ///                &apos;type&apos; =&gt; Segment::class,
        ///                &apos;options&apos; =&gt; [
        ///                    &apos;route&apos; =&gt; &apos;/{{moduleUrl}}[/:action][/:id]&apos;,
        ///                    &apos;constraints&apos; =&gt; [
        ///                        &apos;action&apos; =&gt; &apos;[a-zA-Z][a-zA-Z0-9_-]*&apos;,
        ///                        &apos;id&apos; =&gt; &apos;[0-9]+&apos;,
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigTemplate {
            get {
                return ResourceManager.GetString("ConfigTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///namespace {{moduleName}}\Controller;
        ///
        ///use Zend\Mvc\Controller\AbstractActionController;
        ///use Zend\View\Model\ViewModel;
        ///
        ///class {{moduleName}}Controller extends AbstractActionController
        ///{
        ///    public function indexAction()
        ///    {
        ///        return new ViewModel();
        ///    }
        ///}.
        /// </summary>
        internal static string ControllerTemplate {
            get {
                return ResourceManager.GetString("ControllerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///namespace {{moduleName}};
        ///
        ///class Module
        ///{
        ///    const VERSION = &apos;3.0.2dev&apos;;
        ///
        ///    public function getConfig()
        ///    {
        ///        return include __DIR__ . &apos;/../config/module.config.php&apos;;
        ///    }
        ///}.
        /// </summary>
        internal static string SourceConfigTemplate {
            get {
                return ResourceManager.GetString("SourceConfigTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;{{moduleName}} index&lt;/h2&gt;.
        /// </summary>
        internal static string ViewTemplate {
            get {
                return ResourceManager.GetString("ViewTemplate", resourceCulture);
            }
        }
    }
}
